import TestComponent from "@/components/TestComponent";
import { Metadata } from 'next';
import Link from 'next/link';

export const getStaticProps = async () => {
   return {
      props: {},
   };
};


export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const Page = () => {
   return (
      <div>
         <TestComponent pageName="home" />
         <Link href="/page1">page1</Link>
      </div>
   );
};

export default Page;
